### ISSUE TITLE
test.sh crashes with Message: 'phantomjs' executable needs to be in PATH

### ISSUE THREAD

**Issue by IsaacN72** [test-point/test-capability-locator#1]
Hi,
On a new Ubuntu (16.04) LAMP system the test.sh crashes during execution with the above message. The resolution of the issue seems obvious, but could the test.sh script be modified to test PATH for the phantomjs executable?
Cheers
Isaac

**Comment by monkeypants** [comment]
Good catch, thanks!

**Comment by IsaacN72** [comment]
Issue was (apparently) resolved (apt-get install phantomjs). I'm unsure if I've triggered a false positive through an inadequate installation of phantomjs though (see issue 2) .

**Comment by monkeypants** [comment]
README needs to describe how to ensure the correct phantomjs, that's described in #2 so I'll close this one here (I don't believe there is evidence of another problem, since it works for both of us now that your phantomjs is in order)
