### ISSUE TITLE
test.sh crashes during self-test

### ISSUE THREAD

**Issue by IsaacN72** [test-point/test-capability-locator#2]
Hi again,
The phantomjs issue was easily resolved (apt-get install phantomjs). A new issue appears during the running of test.sh.
Please note that the previous installation directory was deleted (rm -rf) and the installation started from scratch with phantomjs installed to ensure that there were no artefacts from the earlier issues impacting the new installation attempt.
In what appears to be a self-test of the installation, the script crashes during the 'test_update_smp' phase:
client_side/test_query_formation.py .......................
discovery_api/test_dcl_lookup.py .....
management_api/test_update_smp.py FF
=== FAILURES ====
test_log_in_and_see_the_update_form

(two lines appear to be causing issues: management_api/test_update_smp.py:41 and management_api/test_update_smp.py:45:  Same root cause in both 'Webdriver Exception' Apologies if I've put too much spam here!)

Issue #1
management_api/test_update_smp.py:41: 
 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.venv/local/lib/python2.7/site-packages/pytest_bdd/scenario.py:195: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
.venv/local/lib/python2.7/site-packages/pytest_bdd/scenario.py:137: in _execute_step_function
    step_func(**kwargs)
management_api/test_update_smp.py:32: in authenticate
    if 'idp.testpoint.io' in browser.url:
.venv/local/lib/python2.7/site-packages/splinter/driver/webdriver/__init__.py:180: in url
    return self.driver.current_url
.venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:491: in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
.venv/local/lib/python2.7/site-packages/pytest_splinter/webdriver_patches.py:56: in execute
    result = self._base_execute(driver_command, params)
.venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:236: in execute
    self.error_handler.check_response(response)
-----
WebDriverException: Message: Error - Unable to load Atom 'execute_script' from file ':/ghostdriver/./third_party/webdriver-atoms/execute_script.js'

.venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py:163: WebDriverException

Issue #2
management_api/test_update_smp.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.venv/local/lib/python2.7/site-packages/pytest_bdd/scenario.py:195: in _execute_scenario
    _execute_step_function(request, scenario, step, step_func)
.venv/local/lib/python2.7/site-packages/pytest_bdd/scenario.py:137: in _execute_step_function
    step_func(**kwargs)
management_api/test_update_smp.py:32: in authenticate
    if 'idp.testpoint.io' in browser.url:
.venv/local/lib/python2.7/site-packages/splinter/driver/webdriver/__init__.py:180: in url
    return self.driver.current_url
.venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:491: in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
.venv/local/lib/python2.7/site-packages/pytest_splinter/webdriver_patches.py:56: in execute
    result = self._base_execute(driver_command, params)
.venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:236: in execute
    self.error_handler.check_response(response)
---
WebDriverException: Message: Error - Unable to load Atom 'execute_script' from file ':/ghostdriver/./third_party/webdriver-atoms/execute_script.js'

.venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py:163: WebDriverException
----------------------------

Cheers

Isaac

**Comment by monkeypants** [comment]
I assume from #1 that you are using ubuntu, is that right? what version?

What else can you tell me about your environment (to help me reproduce this)?

**Comment by IsaacN72** [comment]
Hi Chris. 
It is Ubuntu 16.04 LTS. Python 2.7.12, openjdk version "1.8.0_111", phantomjs 2.1.1. If there is another system application/service you need information on, please let me know.
R
Isaac

**Comment by monkeypants** [comment]
Maybe it's a problem with the Ubuntu packaged phantomjs, the one I tested with was installed via npm.

Try removing the current phantomjs and doing this:
```
$apt-get install -y nodejs-legacy npm
$npm install -g phantomjs-prebuilt
./test.sh
```

If that works, I might need to add some more info about dependencies to the README :/

**Comment by IsaacN72** [comment]
Hi Chris,
That did the trick: "30 passed in 12.99 seconds", so it looks like Ubuntu's packaged phantomjs doesn't want to play nicely with others. Thanks for your help. I'll be sure to let you know of any other speed bumps I hit.
Cheers,
Isaac

**Comment by monkeypants** [comment]
Actually I'm going to reopen the ticket - we have a documentation bug until the README explains how to install the correct phantomjs.
